# Site
repository: sjuanandres0/sjuanandres0.github.io #/resume-theme #repository: danifranco/danifranco.github.io
favicon: images/search-solid.png #asterisk-solid.png #favicon.ico

# Content configuration version
version: 2

# Personal info
name: Juan Andres SIMONETTI
title: Industrial Engineer keen on Data Science
email: simonettijuanandres@gmail.com
#website: sjuanandres0.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: asd
github_username:  sjuanandres0
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: asd
linkedin_username: juan-andres-simonetti
#kaggle_username: juanandressimonetti
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: kaggle
  icon: fab fa-kaggle
  url: https://www.kaggle.com/juanandressimonetti
- title: medium
  icon: fab fa-medium
  url: https://sjuanandres0.medium.com/
- title: web
  icon: fas fa-globe
  url: sjuanandres0.github.io
- title: telegram
  icon: fab fa-telegram-plane
  url: https://t.me/s0juan
- title: email
  icon: fas fa-at
  url: simonettijuanandres@gmail.com
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000" G-5B1JFM643R 
gtag: "G-5B1JFM643R" #"UA-00000000-0" 
#google_analytics: "G-5B1JFM643R" #"UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Juan and I'm an <mark>Industrial Engineer</mark> keen on <mark>Data Science</mark>.

  I certainly don‚Äôt know everything but I can learn anything (or well... almost anything üôÉ).

  I strongly believe things can always be improved. 

  Can-do and solution seeker mindset.
  
  Team player and motivated by challenges.


content:

#######################
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-right
        title: Short Term Bitcoin Price Prediction with Deep Learning (DL)
        link: github.com/sjuanandres0/crypto
        # link_text: Project Website
        additional_links:
          - title: github
            icon: fab fa-github
            url: https://github.com/sjuanandres0/crypto
          - title: medium
            icon: fab fa-medium
            url: https://medium.com/geekculture/short-term-bitcoin-price-prediction-with-deep-learning-ab4386e84b5
          - title: jupyter
            icon: fas fa-book-open #far fa-bookmark
            url: https://nbviewer.jupyter.org/github/sjuanandres0/crypto/blob/main/Main.ipynb
        quote: >
          <mark>Deep Learning - Keras</mark> <mark>Plotly</mark> <mark>Matplotlib</mark> <mark>SKLearn</mark> <mark>Numpy</mark> <mark>Pandas</mark>
        description: | # this will include new lines to allow paragraphs
          This project was triggered by the Capstone Project of the Udacity Data Scientist Nanodegree Program where I had to put into practice many of the skills learned. The project topic was free so, due to the recent hype in Cryptocurrencies, I decided to work on a Bitcoin Price Predictor using Deep Learning. 
#          Disclaimer: the model and predictions do not pretend to be used as financial advice. They were created for educational purposes and with a time constraint. Do not take financial decisions based on the results.  

      - layout: top-right
        title: ThuisBot (Automated Crawler Bot)
        quote: >
          <mark>Scrapy</mark> <mark>Requests</mark> <mark>RE</mark> <mark>Numpy</mark> <mark>Pandas</mark>
        description: | # this will include new lines to allow paragraphs
          ThuisBot is a script that periodically scraps websites gathering relevant information about new houses for sale and sends automatic messages via Telegram when a new house matches the set criteria (considering value, square meters, age of the property, energy label, among others). 
          Unfortunately, I can't disclose the code, but it's built using Scrapy, Pandas, Numpy, Requests, Regular Expression and GitHub Actions.
          The project was driven by a personal need.

      - layout: top-right
        title: Disaster Response Pipeline Project (ML-NLP, Flask)
        link: github.com/sjuanandres0/disaster_response_pipeline_project
        # link_text: Project Website
        additional_links:
          - title: github
            icon: fab fa-github
            url: https://github.com/sjuanandres0/disaster_response_pipeline_project
        quote: >
          <mark>SQLAlchemy</mark> <mark>NLTK</mark> <mark>RE</mark> <mark>SKLearn</mark> <mark>Pickle</mark> <mark>Numpy</mark> <mark>Pandas</mark>
        description: | # this will include new lines to allow paragraphs
          This project consists of an API that classifies disaster messages. 
          For this purpose, a Machine Learning model using NLTK was trained with a labelled dataset provided by [Figure Eight](https://www.figure-eight.com/), saved in a pickle file and embedded in a webapp using Flask and Heroku. 
          Users/pipelines are then able to use the trained model to classify messages according to the type of assistance required. 
          With supervised learning, a Machine Learning model using NLTK library was trained in a labelled dataset provided by Figure Eight. 
          This project was promoted/facilitated by Udacity in the Data Scientist program.

      - layout: top-right
        title: COVID19 - Countries Wealth, Cases, Deaths and Vaccines (Analytics)
        link: github.com/sjuanandres0/covid19
        # link_text: Project Website
        additional_links:
          - title: github
            icon: fab fa-github
            url: https://github.com/sjuanandres0/covid19
          - title: medium
            icon: fab fa-medium
            url: https://sjuanandres0.medium.com/covid-19-countries-wealth-cases-deaths-and-vaccines-ff7fa8a83b1b
          - title: jupyter
            icon: fas fa-book-open #far fa-bookmark
            url: https://nbviewer.jupyter.org/github/sjuanandres0/covid19/blob/master/COVID-19_WealthCasesDeathsVaccines.ipynb
          - title: kaggle
            icon: fab fa-kaggle
            url: https://www.kaggle.com/juanandressimonetti/covid-19-countries-wealth-cases-deaths-and-vacc
        quote: >
          <mark>Plotly</mark> <mark>Seaborn</mark> <mark>Missingno</mark> <mark>SKLearn</mark> <mark>Numpy</mark> <mark>Pandas</mark>
        description: | # this will include new lines to allow paragraphs
          This project was part of the Udacity Data Scientist Nanodegree where it was required to write a Data Analytics blog post from a topic of my choice. I decided to work on COVID-19 data trying to reply questions that were particularly interesting for me. This project was very useful to learn how to gather real world data in the huge internet and generate interactive visualizations with Plotly. Additionally, I used Numpy, Pandas, SKLearn, Missingno and Seaborn. 

      - layout: top-right
        title: COVID19 - Dashboard (Analytics)
        link: github.com/sjuanandres0/sja-covid19-webapp
        # link_text: Project Website
        additional_links:
          - title: github
            icon: fab fa-github
            url: https://github.com/sjuanandres0/sja-covid19-webapp
          - title: webapp
            icon: fas fa-chart-line
            url: https://sja-covid19-webapp.herokuapp.com/
        quote: >
          <mark>Flask</mark> <mark>Heroku CI/CD</mark> <mark>HTML</mark> <mark>CSS</mark> <mark>jQuery</mark> <mark>Plotly</mark> <mark>Numpy</mark> <mark>Pandas</mark>
        description: | # this will include new lines to allow paragraphs
          This project consist of building a webapp to practise software engineering skills. 
          It consists of a tailormade COVID-19 Dashboard that updates automatically.
          It's hosted in Heroku and it's feeded from Our World in Data.
          This project was promoted/facilitated by Udacity in the Data Scientist program.

      - layout: top-right
        title: IBM Recommendations with Natual Language Processing (NLP)
        link: github.com/sjuanandres0/Recommendations_with_IBM
        # link_text: Project Website
        additional_links:
          - title: github
            icon: fab fa-github
            url: https://github.com/sjuanandres0/Recommendations_with_IBM
        quote: >
          <mark>NLTK</mark> <mark>SKLearn</mark> <mark>Pickle</mark> <mark>Matplotlib</mark> <mark>RE</mark> <mark>Numpy</mark> <mark>Pandas</mark>
        description: | # this will include new lines to allow paragraphs
          In this project I analyzed the interactions that users have with articles on the IBM Watson Studio platform and made recommendations to them about new articles I think they will like. For this purpose, I used NLTK library to process text data and provide recommendations based on Rank, User-User Collaborative Filtering, Content and Matrix Factorization.
          This project was promoted/facilitated by Udacity in the Data Scientist program.

      - layout: top-right
        title: Acea Smart Water Analytics, River Arno hydrometry (ML-XGBoost)
        link: kaggle.com/juanandressimonetti/cmp-acea-smart-water-analytics
        # link_text: Project Website
        additional_links:
          - title: kaggle
            icon: fab fa-kaggle
            url: https://www.kaggle.com/juanandressimonetti/cmp-acea-smart-water-analytics
        quote: >
          <mark>XGBoost</mark> <mark>SKLearn</mark> <mark>Seaborn</mark> <mark>Missingno</mark> <mark>Matplotlib</mark> <mark>Numpy</mark> <mark>Pandas</mark>
        description: | # this will include new lines to allow paragraphs
          In this project I predicted the Hydrometry (river level) of River Arno (Italy) considering historical records of Rainfall and Temperature in different geographical points. The Machine Learning algorithm used was XGBoost. 
          This project is part of a Kaggle Analytics Competition.
          
#######################
  - title: Working Experience 
    layout: list
    content:
      - layout: left
        title: Industrial Engineer
        link: FedEx.com
        # link_text: boringcompany.com
        sub_title: FedEx #[FedEx](https://www.FedEx.com/)
        caption: January 2020 - Present
        description: | # this will include new lines to allow paragraphs
            - Developed a SQL+Python tool to improve accuracy, scalability and speed of P2O transit times maintenance.
            - Support management with the analysis, interpretation and application of complex information.
            - Plan and execute location and routing system updates in support of operational changes.
            - Coordinate planning for system updates with colleagues and stakeholders in the field and central network.

      - layout: left
        title: Project Manager
        link: mr-marinegroup.com
        # link_text: boringcompany.com
        sub_title: MR Marine Group
        caption: July 2019 - January 2020
        description: | # this will include new lines to allow paragraphs
            - Responsible for the successful completion of inspection and repair projects on marine elevators worldwide. 
            - Independently analysing elevator problems and assigning right S/E and materials needed.
            - Customer liaison, preparing proposals, planning of work, organizing and coordinating projects.
            - Contact with customers, sub-contractors, material suppliers, shipping agents, forwarders, port authorities. 

      - layout: top
        title: Industrial Engineer
        link: Dopert.com.ar
        # link_text: boringcompany.com
        sub_title: Dopert Metal
        caption: September 2017 - March 2019
#        description: | # this will include new lines to allow paragraphs

      - layout: top
        title: Dealer Development Intern
        link: JohnDeere.com
        # link_text: boringcompany.com
        sub_title: John Deere
        caption: October 2015 - March 2017
#        description: | # this will include new lines to allow paragraphs


#######################
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Data Scientist
        caption: 2021
#        sub_title: Udacity Nanodegree
        link: https://www.udacity.com/course/data-scientist-nanodegree--nd025
        link_text: Udacity Nanodegree
#        description: | # this will include new lines to allow paragraphs
#           Got theory and hands-on experience in real world Data Science projects. 

      - layout: top
        title: Industrial Engineer
        caption: 2012-2018
#        sub_title: Universidad Nacional de Rosario 
        link: https://web.fceia.unr.edu.ar/es/ingenier%C3%ADa-industrial.html
        link_text: Universidad Nacional de Rosario
#        description: | # this will include new lines to allow paragraphs
#           Final project: ‚ÄúTechnical and economic feasibility studies of an aluminium trailer company‚Äù.

#######################
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      When not in front of the screen, I am climbing, cycling, cooking (maybe BBQing) or learning chess/dutch.

#      Look at this cool image  
#      ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag